server:
  # Порт, на котором поднимается HTTP API сервиса.
  port: 8080

spring:
  config:
    activate:
      on-profile: test

    # В prod конфигурация сервиса загружается из Spring Cloud Config Server.
    # Import НЕ optional: если Config Server недоступен — сервис не должен стартовать.
#    import: "configserver:"

  cloud:
    config:
      # Несколько Config Server'ов: клиент попробует их по очереди.
#      uri: http://j-srv-config:8080,http://j-srv-config.production.svc:8080,http://j-srv-config.test.svc:8080,http://j-srv-config.pay-service.svc:8080,https://j-srv-config.prod.payk8s.transcapital.com
      label: main
      fail-fast: true

      # Retry при старте (актуально при fail-fast=true).
      retry:
        max-attempts: 6
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000

## =========================
## Logging
## =========================
logging:
  level:
    root: INFO
    ru.copperside.controlledpersonsregistry: INFO
